### ISSUE TITLE
overflow-wrap

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/GitHub-code-wrap#1]
I found [this example](https://github.com/mathiasbynens/unicode-9.0.0/blob/master/Block/Arrows/symbols.js) where this css doesn't wrap the code properly.

If I add `overflow-wrap: break-word;` it *sort of* fixes it:

```css
@-moz-document domain("github.com"), domain("gist.github.com") {
.blob-code-inner,
  .markdown-body pre > code,
  .markdown-body .highlight > pre {
    white-space: pre-wrap !important;
    word-break: break-all !important;
    overflow-wrap: break-word !important;
    display: block !important;
  }
  td.blob-code-inner {
    display: table-cell !important;
  }
}
```

 Oddly in Chrome, the scroll bar still appears. I wonder if there is a better solution.
